### ISSUE TITLE
Automatic Merging

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#102]
There should really be some type of Scrum Master who's helping the Lead Developer by automatically merge & assigning the developers & designers to finish the job. 

When you're accepting a Tier 2 job or higher there should be a button that says "Assign to Scrum Master" or similiar. This Scrum Master is already assigned to one Manager, and therefore he's also connected to the workers that the manager is in charge of. 

When you go over T1 everything goes too fast, there really needs to be some type of automation.

**Comment by jhovgaard** [comment]
It is now possible to auto repeat for Lead Devs. Do you think this fixes this issue?

**Comment by BrutalCSkakan** [comment]
I think this works for now. I've started to get "the game going" pretty good now.

**Comment by InDieTasten** [comment]
So I guess the initial feature request is not going to be persued then. Gonna close it for now
