### ISSUE TITLE
Keep Jobs tab open when accepting a job offer

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#106]
Usually you accept more than one job at the time, therefore the Job modal window should be kept open when you've accepted a job. 
Right now you Click on the job button -> Click on the job -> accept ->Click on the job button -> Click on the job -> accept -> ETCETC.

**Comment by InDieTasten** [comment]
@jhovgaard please schedule as you wish into some milestone

**Comment by jhovgaard** [comment]
Beta 6 and now in progress

**Comment by jhovgaard** [comment]
Redesign required. Current one very sucky.

**Comment by jhovgaard** [comment]
Implemented brand new contract/job view.
