### ISSUE TITLE
Can't connect several "rooms" with the Glass Walls

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#107]
Right now we have the straight glass(the "I" piece), and then we have the corners(the "L" piece). I want rooms next to each others but these cant be fully connected, we need a "T" piece, and also a "X" piece! :)

**Comment by InDieTasten** [comment]
I :+1: +1 this :)

**Comment by BrutalCSkakan** [comment]
Actually the only thing that should be in the shop is the "X" piece. it should then adapt to its connected walls. 
I dunno if the word is correct, but it should behave as the "Origo".

**Comment by InDieTasten** [comment]
Maybe only normal wall that will wrap whenever possible? So in the shop it's only wall, and it will always connect to neighbooring walls, including actual walls of the floor

**Comment by jhovgaard** [comment]
T and X piece is included in Beta 6.
