### ISSUE TITLE
Bottom icons numbers out of div if over ~100

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#111]
My inventory isn't showing the numbers correctly, I'd say that a rectangle would fit better, rather than a circle. 

Current: 
![image](https://cloud.githubusercontent.com/assets/8394703/19279072/fe089c50-8fdf-11e6-8826-bde038b86dfd.png)

My idea: 
![image](https://cloud.githubusercontent.com/assets/8394703/19279180/9b1420b4-8fe0-11e6-97b3-396bd54c1cac.png)

**Comment by InDieTasten** [comment]
I'd suggest a cap of 99, and if it's any higher than that, just show 99+. If scaled a bit smaller this should still fit nicely into a circle. ;)
This way the width would be more predictable. you are just shifting the problem to any later point, where your rectangle goes off into neighboring buttons again.

**Comment by BrutalCSkakan** [comment]
I dunno if I agree on the 99+ as I'm always over 99+ items in my inventory. 
This means that the numbers on the inventory is totally useless for me.

**Comment by InDieTasten** [comment]
I'll label this an enhancement for now, as it's not affecting all players. Only players with more than 99 items in inventory, which to me seems rather unusual.

**Comment by InDieTasten** [comment]
And it's also only visual. no functionality is missing or blocking

**Comment by jhovgaard** [comment]
Removed it, didn't really bring any value indicating the amount.
