### ISSUE TITLE
Deadline-timer runs during pause?

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#112]
I paused my game around 00.00 this night.. When I paused the game I did it with one active job that had around 300 hours until deadline. 
When I came back today it still looked like it should. 
But then I clicked on 3 (fast-forward) and the job dissapeared after around 1-2 seconds. It behaved like the deadline-timer actually keeps counting even if the game is set on pause.

Can try to reproduce during the night.

**Comment by jhovgaard** [comment]
That sounds weird! Might be if I'm accidently comparing with system time instead of game time. Let's see if we can reproduce.

**Comment by BrutalCSkakan** [comment]
Haven't been able to reproduce yet.

**Comment by jhovgaard** [comment]
Let's close this for now, until we are able to reproduce.
