### ISSUE TITLE
No progressbar when a worker is on vacation

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#114]
No progressbar when a worker is on vacation

**Comment by jhovgaard** [comment]
You want me to remove it? The progressbar should show when employee is back.

**Comment by BrutalCSkakan** [comment]
Nono, more like adding a timer when the person is on vacation. The progressbar should show the vacation-progress so I know when he's/she's coming back

**Comment by jhovgaard** [comment]
Fixed. Indicator was only showing if employee had an active task while sent on vacation.
