### ISSUE TITLE
Quick clicking a new dev.research component in a modal is bugged

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#119]
Oh these titles, how should they be described better?!

Oh well.
When I'm playing around and clicking up a modal window and tries to buy something quick it doesn't react. 
For instance you can try with:
1. Get a developer
2. Get yourself ready!
3. Open the developer 
4. Click on UI Component
5. Click "fast" on "Confirm"
6. The event didn't go off

[noreaction.zip](https://github.com/hovgaardgames/developertycoon/files/531412/noreaction.zip)

**Comment by jhovgaard** [comment]
Need to do our own implementation of Angular Modals. The one currently used is bugged and no more maintained.

**Comment by jhovgaard** [comment]
Fixed both Confirm and Message dialog. You can now click as fast as you want.
