### ISSUE TITLE
Grid issue with "aligning" objects 

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#120]
You've spoken about the rework of the Grid system. I dunno if this is included in the fix tho!

The "marked" guy sits close to his friends
![image](https://cloud.githubusercontent.com/assets/8394703/19413380/a61d3e70-932b-11e6-9d2f-9ecdbdc79f5a.png)

This guy is sitting a mile away from his friends
![image](https://cloud.githubusercontent.com/assets/8394703/19413385/b935ef5c-932b-11e6-926d-b350441c032d.png)

**Comment by InDieTasten** [comment]
To me it seems you've just placed him one tile away from his friends. If you did so, I'm sure this is intended behaviour.

**Comment by BrutalCSkakan** [comment]
Oh yeah, actually he's one tile away. 
There's ~10 pixels that I have to touch in order to get him into the right tile, by other words it's really hard to fit the desk onto the right tile. 

Shouldn't we be able to have some type of "listener" that makes everything "click-through" when you're in the "move-item" mode?

**Comment by InDieTasten** [comment]
Feel free to open another issue to address "placing of objects should not be prevented when other objects obscure an otherwise free tile", if thats actually what you are trying to say :)
