### ISSUE TITLE
Jobs with Web Frontend Modules on T4, but I can't get Lead Devs until T5

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#121]
Jobs with Web Frontend Modules on T4, but I can't get Lead Devs until T5

![image](https://cloud.githubusercontent.com/assets/8394703/19452505/95155266-94b1-11e6-99d0-07d1115c658c.png)

**Comment by jhovgaard** [comment]
Fixed!
