### ISSUE TITLE
Add: Show deadline in the Jobs view

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#123]
I'm a tactical person, therefore I will NOT take the jobs with low deadline in the cases when I dont have all the modules already done. 
But I have no problems with taking these with lower deadline if I already have the modules ready.

So I'd like to have the deadline showing in the joblist view, can I haz dis pls?

**Comment by jhovgaard** [comment]
Indeed sir :-)

**Comment by jhovgaard** [comment]
Fixed
