### ISSUE TITLE
CTO products still update even if there's no CTO left in the company

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#126]
So, I created a CTO quickly and saw that it wasn't developed as much as I hoped so I deleted him after a minute. 
I did however have the time to create a new product before I removed the CTO from the company. 

Now my console is filled with [22:46:18] Added 0 users to Test (Web) which I think is thrown by the CTO products? Can it be that the product still generates everything, even if there's no CTO at the company? Is this intended?

**Comment by jhovgaard** [comment]
It's absolutely true, that's how it works. We have to figure out a way to solve this.

**Comment by jhovgaard** [comment]
Fixed for now. Both users growth and payout is paused while no CTO.
