### ISSUE TITLE
Update Employees View

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/developertycoon#131]
Show relevant data like current task + progress instead of speed and salary.

**Comment by jhovgaard** [comment]
My suggestion is the following columns:
EmployeeType, Name, Mood, Current Task (progress)

Also I want to make the employee dropdown available (same as when looking at a specific employee).

**Comment by NoraNava** [comment]
I think one more of main columns would be salary, or that would be only under the dropdown?

**Comment by jhovgaard** [comment]
Completed first version. Might be good enought, might not be. Let's reopen if needed.
