### ISSUE TITLE
Stacking components, modules and products

### ISSUE THREAD

**Issue by WodeCraft** [hovgaardgames/developertycoon#134]
It would be nice if the different components, modules and products that are in the inventory could stack up. Instead of having a ton of "UI Components" you just have one with a number indicating the actual amount.

**Comment by BrutalCSkakan** [comment]
They do stack up in Beta 6 :)

**Comment by jhovgaard** [comment]
@WodeCraft we think alike. As @BrutalCSkakan says it's been implemented in Beta 6 :-)

**Comment by InDieTasten** [comment]
Duplicate of #68
