### ISSUE TITLE
Writing an e-mail: keyboard strokes fallthrough

### ISSUE THREAD

**Issue by WodeCraft** [hovgaardgames/developertycoon#136]
When writing an e-mail the keyboard strokes "fall through" to the game, so every press on space will result in the game pausing or starting. And using ASDW will make the camera move around.

Is it possible to keep the keyboard strokes to not impact the game?

**Comment by jhovgaard** [comment]
Fixed! :-)

**Comment by InDieTasten** [comment]
Pretty sure there was an issue like that before, but I couldn't find it :(

**Comment by jhovgaard** [comment]
@InDieTasten It was fixed already, so you're right :)
