### ISSUE TITLE
Show progress of needed modules/components inside Contracts

### ISSUE THREAD

**Issue by Zolor** [hovgaardgames/developertycoon#144]
You are required to toggle a lot between Contracts and Inventory. To see what modules/components you need and what modules/components you currently have. To simplify this there could be a progress inside Contracts. I made a mock-up http://i.imgur.com/j6Yazf1.png
The box showing requirements is right now faded with the rest of the box that you haven't filled requirements for yet. This makes it really hard to see what the number required actually is. Would be nice if this "number required box" was not faded for clarification while the rest of the box still is faded.

**Comment by jhovgaard** [comment]
Done
