### ISSUE TITLE
Add employee photos to all views

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/developertycoon#156]
* Hiring view
* Select employee for workstation

**Comment by BrutalCSkakan** [comment]
Should this be generated by some type of standard template with random colors? Or should it be done by hand? 
I'd like to see this: http://www.avatarsinpixels.com/
Something even more awesome would be if the followers/subscribers of your stream get the chance to do their own pixel that will be in the game?

**Comment by jhovgaard** [comment]
Implemented by showing the actual employee.

Brutal, I think it's gonna be too hard doing a version that fits the game assets since their detail level is very high. Pixel art won't do :(
