### ISSUE TITLE
Improve job offer slider for cost-per-hour

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/developertycoon#25]
I find it quite difficult to set the desired cost/hour in my job offers.
I don't know how you want to approach this. Maybe buttons to the left and right of the slider, to increase/decrease by 7.5%.
Maybe an overall bigger slider. I'm not too sure.
I also don't know considerations for input methods. It seems you are focusing on mouse interfaces, with some keyboard inputs for naming devkits, the company name and allocating research points to devkits. So maybe there's a chance for keyboard input for Cost/Hour as well?

---
First seen on reddit: https://www.reddit.com/r/developertycoon/comments/4ums2l/enhancement_costhour_slider_difficult_to_get_right/

**Comment by jhovgaard** [comment]
Fxied by extending the slider + adding a textbox
