### ISSUE TITLE
Newly assigned manager menu bug

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/developertycoon#26]
Seems to be a problem with the manager menu, picture,
http://prntscr.com/bxm5q7
![image](https://cloud.githubusercontent.com/assets/7047377/17192251/ef16161e-544d-11e6-9595-a2fa9644fcbb.png)

:edit:
This only happens when you have just placed the manager, and use the menu. When you click out of it, todo something else, the menu seem to work correctly.

---
First seen on reddit:
https://www.reddit.com/r/developertycoon/comments/4unkha/bug_manager_menu/

**Comment by jhovgaard** [comment]
Fixed by changing from custom-made dropdown to https://github.com/jseppi/angular-dropdowns.
