### ISSUE TITLE
Competition comparison not intuitive

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/developertycoon#27]
It really needs to be easier to understand that you can click on each of the company names, to get more information from them.
http://prntscr.com/bxu0ef
![image](https://cloud.githubusercontent.com/assets/7047377/17192314/30f90a50-544e-11e6-82b1-16496a34c806.png)

---
First seen on reddit: https://www.reddit.com/r/developertycoon/comments/4uq55r/suggestion_easier_to_understand_competition/

**Comment by InDieTasten** [comment]
If this is included in beta 4 release, please move back to beta 4 milestone and close.

**Comment by jhovgaard** [comment]
New competition view implemented.
