### ISSUE TITLE
Team productivity slows down as team size increases

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/developertycoon#37]
Modeling the real-life requirement for larger teams to have meetings on evaluation, convention, and similar things.

Terminology:
A team consists of ALL developers, that are working on one job.

Developers should have a "collaborative" factor which determines, how much they decrease the productivity gain of the team.

The team productivity is the (sum of the team member's productivities) multiplied by the product of all team member's collaborative factor.

The collaborative factor may start at about `0.88` and can be increased by researching collaborative technologies (like modular development, project management, splitting work, soft skills, scrum, you name it) up to I don't know... maybe `0.98`

You can tweak the numbers however you want, but that's the basic idea putting in some powers to the factor to make it more or less affecting, or cropping the resulting to a specific range. Math shit you know :D

---
First seen on reddit: https://www.reddit.com/r/developertycoon/comments/4ur39g/suggestion_team_productivity_slows_down_as_team/

**Comment by jhovgaard** [comment]
I believe the complexity of this will kill the message after we added the crafting system. I'll close the suggestion for now, but keep it in the back of my head when we hit end-game development.
