### ISSUE TITLE
Will there only ever be outsourcing and devkits?

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/developertycoon#39]
I kind of miss making my own products and maintaining those. Also I feel like having only my office to expand for newly hired employees, completing jobs and making devkits, is a bit thin.

I would like to "make" something other than a company. Thats all I ever do as of Beta 3 and 4. Trying to make a successful company.

What about break-fix support for jobs? So when I deliver a relatively low quality "service/product", it's likely to break in the future, needing revamp. So having long-term contracts with clients over certain services and products. I would enjoy that. Not sure about the exact mechanic, but the idea I do like.

**Comment by jhovgaard** [comment]
Totally agree, we need to build more complexity especially when you hit Tier 2.

I've been playing around with redesigning the Client Executive part to include long-term contracts after completing a specific amount of jobs.

I'll come up with an idea. Feel free to do the same :-)

**Comment by jhovgaard** [comment]
Update: We now include fixed price, limited RFQ and full RFQ job types. They come for each tier.

I think we still need to be able to do contracts, but don't know how to design it yet.
