### ISSUE TITLE
Employment always shows 0 days

### ISSUE THREAD

**Issue by bretterer** [hovgaardgames/developertycoon#55]
The length of an employee always shows 0 days

<img width="364" alt="screen shot 2016-08-18 at 4 26 11 pm" src="https://cloud.githubusercontent.com/assets/1906920/17789524/8f82f90a-6560-11e6-83fa-cba84eaa4524.png">

**Comment by jhovgaard** [comment]
Fixed (only working for employees hired after this commit).
