### ISSUE TITLE
Deliver project removes ALL Components that match

### ISSUE THREAD

**Issue by bretterer** [hovgaardgames/developertycoon#61]
I built 2 "Simple Blog Website's" and delivered a project for a Simple Blog Website.  Opened my inventory and both of the Simple Blog Website's were gone.  It appears to be delivering all items that match what is requested instead of just 1 from inventory

**Comment by Polymeth** [comment]
Same bug for "Static website"

**Comment by jhovgaard** [comment]
Fixed!
