### ISSUE TITLE
A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by nubii** [hovgaardgames/developertycoon#65]
Uncaught Exception:
Error ENOENT: no such file or directory, mkdir "C:/Users/username/Documents/Developer Tycoon"

at Eroor (native)
![untitled-1](https://cloud.githubusercontent.com/assets/8223988/18251588/27c666e8-738a-11e6-9161-4ead104ff012.jpg)

**Comment by nubii** [comment]
I have played Beta one and now wanted to play beta 5, i have tried running as admin that does not work either.

**Comment by jhovgaard** [comment]
@nubii Interesting. Do the following path exist on your machine? 

    %USERPROFILE%\Documents

If yes, do you have a `Developer Tycoon` folder in that folder?

**Comment by nubii** [comment]
No i do not, the only way i can see my documents is through the shortcut

Libraries\Documents

**Comment by jhovgaard** [comment]
@nubii Just to make sure, you don't have the following folder on your machine: `C:\Users\<Username>\Documents`?

**Comment by nubii** [comment]
Yes

**Comment by nubii** [comment]
My files are backed up

\\*Extra Drive*\Files\Users\*username*\Files\My Documents\

But other games have no problem with this

**Comment by jhovgaard** [comment]
@nubii alright that is the reason then. Definitely a bug. I'll get it fixed for next release. For now, you can temporary fix it by creating the Documents folder in your user profile directory :-)

**Comment by jhovgaard** [comment]
Fixed and implemented.
