### ISSUE TITLE
T2 Sales Executive Bug (giving T2 job when set to search for T1)

### ISSUE THREAD

**Issue by xSARDON** [hovgaardgames/developertycoon#67]
I have a T2 sales execute in an T2 workstation. I define him to look for T1 jobs, but he will always return T2 jobs.
The overlay above him shows "Tier 1 job" but in the end he will return T2 job.

Test environment:
1 T1 sales executive in an T1 workstation.
1 T2 sales executive in an T2 workstation.
Define both to look for T1 job. the T2 worker will return T2 jobs.

If u disable the T1 worker, the T2 will sometimes return T1 jobs and sometimes T2 jobs.

**Comment by jhovgaard** [comment]
Duplicate sorry. Already fixed.

**Comment by InDieTasten** [comment]
Actually, this should be the original. Just for referenced I searched for the actual "duplicate" issue, which is #75 so here I go, marking this as the original

**Comment by InDieTasten** [comment]
@xSARDON Thank you for providing the issue you encountered, and I think I can tell you in the name of jonas, that he appreciates you and is sorry to have labeled this duplicate. The issue is already fixed and will no longer as of Beta 6 release
