### ISSUE TITLE
Objects - Tier 2 Desk display sprite overextends monitor mesh

### ISSUE THREAD

**Issue by dakrisis** [hovgaardgames/developertycoon#79]
![screenshot-001](https://cloud.githubusercontent.com/assets/617231/18827740/9bd6a886-83d4-11e6-9889-d3b5b5b66e2a.png)
![screenshot-002](https://cloud.githubusercontent.com/assets/617231/18827741/9f9ee7da-83d4-11e6-808d-5b29a9069f96.png)

**Comment by jhovgaard** [comment]
Fixed.
