### ISSUE TITLE
Objects - Mounted TV falls behind other object

### ISSUE THREAD

**Issue by dakrisis** [hovgaardgames/developertycoon#80]
![screenshot-003](https://cloud.githubusercontent.com/assets/617231/18827784/db10a768-83d4-11e6-9913-d5321456d677.png)

**Comment by InDieTasten** [comment]
I think this going to be a nightmare for jonas. He would need to split multi-tile object sprites to their parts for the ordered rendering to work as expected.

**Comment by jhovgaard** [comment]
You're right, it's gonna be, but we have to fix it :D

**Comment by dakrisis** [comment]
Just put a higher z-index on it. (sarcasm detected)

**Comment by jhovgaard** [comment]
Fixed

**Comment by InDieTasten** [comment]
Wait what?!! Nice job then! :D
