### ISSUE TITLE
Gameplay - T3 achieved condition confusion

### ISSUE THREAD

**Issue by dakrisis** [hovgaardgames/developertycoon#86]
When I reached Tier 3, my *Company reputation* showed 11829 / 25000, which I believed to be the requirement for leveling up a tier.

So now I have no clue what the actual requirement was. My guess now is I reached a money balance of $150,000+.

**Comment by InDieTasten** [comment]
Pretty sure this is based on reputation only. Once you get a certain reputation, like e.g. 10,000 for T3, the progress for the next milestone T4 is displayed. This is based on a later version I played and the numbers are out of my head meaning not necessarily accurate

**Comment by dakrisis** [comment]
Cool, I guess I never payed attention to the actual amount of reputation needed for T3, but as you say, the next tier barrier is updated in the UI directly. I will keep an eye on this in the next playthrough.
