### ISSUE TITLE
Gameplay - Zooming moves center of view to right / left

### ISSUE THREAD

**Issue by dakrisis** [hovgaardgames/developertycoon#88]
Zooming moves center of view to NW or SE so you always have to re-adjust the center of view.

Or it's just my eyes ;P

**Comment by InDieTasten** [comment]
@dakrisis jonas will hate you for this one :D

**Comment by dakrisis** [comment]
I reckoned it would be tricky to get this right, it's not a game breaking issue fortunately ...

**Comment by InDieTasten** [comment]
It's actually just a bunch of math. I'm sure jonas will be ready to take yet another shot at some point :D

**Comment by jhovgaard** [comment]
Zooming moved to options. Disabled wheel input.
