### ISSUE TITLE
File already exists when changing volume

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/developertycoon#94]
The volume was really high when starting a new game, I lowered the master volume and it worked. Then I lowered the SFX volume and then the game crashed. 

![image](https://cloud.githubusercontent.com/assets/8394703/19216508/e1d87c1c-8dbe-11e6-8752-c3b561aa41fa.png)

**Comment by jhovgaard** [comment]
Seems to be fixed in B6.
