### ISSUE TITLE
No new jobs available after the first one

### ISSUE THREAD

**Issue by joakimbugge** [hovgaardgames/developertycoon#99]
When I started the game I had _one_ job available. I failed to complete this job and now the jobs list has stayed empty for 7 days. Are the jobs supposed to appear automatically or am I missing something crucial?

**Comment by InDieTasten** [comment]
@jhovgaard If this is not intended behaviour, feel free to turn this into p:normal t:bug :)

**Comment by joakimbugge** [comment]
Discard this issue. I did not hire a sales executive ;) I will try and keep my issues to actual bugs from here on.

**Comment by InDieTasten** [comment]
@joakimbugge No worries^^ We are happy to have community members like you to help us out. A wrongfully issued report or two are not the end of the world. I think we'd rather have some noise instead of nothing, so you don't need to hesitate ;)
